export const RRF_K = 60; // Reciprocal Rank Fusion constant
export const MAX_CHUNK_SIZE = 800; // Characters per chunk for splitting
export const OVERLAP_SENTENCES = 1; // Overlapping sentences between adjacent chunks

// Vietnamese Synonym Map for Full-Text Search query expansion
export const SYNONYM_MAP: Record<string, readonly string[]> = {
  phép: ["nghỉ phép", "ngày phép", "annual leave", "nghỉ", "phép năm"],
  lương: ["mức lương", "khung lương", "compensation", "salary", "trả lương", "lương cơ bản"],
  nghỉ: ["nghỉ phép", "nghỉ ốm", "vắng mặt", "leave", "nghỉ việc"],
  ốm: ["nghỉ ốm", "sick leave", "bệnh", "y tế"],
  "làm thêm": ["overtime", "OT", "làm thêm giờ", "tăng ca"],
  "tăng ca": ["overtime", "OT", "làm thêm giờ", "làm thêm"],
  "từ xa": ["remote", "WFH", "làm việc từ xa", "work from home"],
  "thiết bị": ["laptop", "equipment", "tài sản", "máy tính"],
  "truy cập": ["access", "quyền truy cập", "security", "bảo mật"],
  onboarding: ["nhận việc", "bắt đầu", "nhân viên mới"],
  offboarding: ["nghỉ việc", "thôi việc", "rời công ty"],
  "thăng tiến": ["promotion", "cấp bậc", "lên cấp", "E4", "E5"],
  junior: ["cấp bậc", "E3", "level", "entry"],
  senior: ["E4", "cấp bậc", "level", "engineer"],
  "đánh giá": ["performance", "review", "hiệu suất", "calibration"],
  "chi phí": ["expense", "hoàn trả", "công tác", "travel"],
  "nhân viên mới": [
    "onboarding",
    "nhận việc",
    "thiết bị",
    "laptop",
    "truy cập",
    "access control",
    "new employee",
  ],
  "bắt đầu": ["onboarding", "nhận việc", "start date", "nhân viên mới"],
  "quản lý": ["manager", "phê duyệt", "approval"],
  "thai sản": ["parental leave", "maternity", "paternity", "nghỉ thai sản"],
  "thứ bảy": [
    "thứ bảy",
    "thứ 7",
    "chủ nhật",
    "cuối tuần",
    "ngày nghỉ",
    "lịch làm việc",
    "ngày làm việc",
    "giờ làm việc",
    "working hours",
  ],
  "thứ 7": [
    "thứ bảy",
    "thứ 7",
    "chủ nhật",
    "cuối tuần",
    "ngày nghỉ",
    "lịch làm việc",
    "ngày làm việc",
    "giờ làm việc",
    "working hours",
  ],
  "chủ nhật": [
    "thứ bảy",
    "thứ 7",
    "chủ nhật",
    "cuối tuần",
    "ngày nghỉ",
    "lịch làm việc",
    "ngày làm việc",
    "giờ làm việc",
    "working hours",
  ],
  "cuối tuần": [
    "thứ bảy",
    "thứ 7",
    "chủ nhật",
    "cuối tuần",
    "ngày nghỉ",
    "lịch làm việc",
    "ngày làm việc",
    "giờ làm việc",
    "working hours",
  ],
};
